# Generated by Django 5.2.1 on 2025-05-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='linkedin_verified',
            field=models.BooleanField(default=False),
        ),
    ]
