# Generated by Django 5.2.1 on 2025-05-21 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0009_source_statistic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='label',
        ),
    ]
