# Generated by Django 5.2.1 on 2025-05-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0010_remove_statistic_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
