# Generated by Django 5.2.1 on 2025-05-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0011_customuser_company_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='source',
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company_website',
            field=models.URLField(blank=True, default=False),
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
