# Generated by Django 5.2.1 on 2025-05-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='no_linkedin',
            field=models.BooleanField(default=False),
        ),
    ]
