# Generated by Django 4.2.21 on 2025-05-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0013_remove_customuser_company_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stripepayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Stripe Payment', 'verbose_name_plural': 'Stripe Payments'},
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stripepayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='currency',
            field=models.CharField(default='usd', max_length=3),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterModelTable(
            name='stripepayment',
            table='stripe_payments',
        ),
    ]
