# Generated by Django 5.2.1 on 2025-05-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0014_alter_stripepayment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VimeoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255, unique=True)),
                ('video_url', models.URLField()),
                ('is_public', models.BooleanField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
