# Generated by Django 4.2.22 on 2025-06-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0017_chatroom_adminprofile_message_usermembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='iswebinarformfilled',
            field=models.BooleanField(default=False),
        ),
    ]
