# Generated by Django 5.2.1 on 2025-06-11 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0020_message_message_type_message_reply_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='sender',
        ),
    ]
